# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
  lint:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
  type-check:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Type Check
          command: yarn type-check
  test:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Jest Testing
          command: yarn test      
  deploy:
    docker:
      - image: circleci/node:fermium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Assume Github Role
          command: 'git config --global user.email "lshadler13@gmail.com" && git config --global user.name "lshadler"'
      - run:
          name: Deploy to server
          command: yarn deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - type-check:
          filters:
            branches:
              ignore:
                - master
      - test:
          filters:
            branches:
              ignore:
                - master
      - lint:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          requires:
            - build
            - test
            - type-check
            - lint
          filters:
            branches:
              only:
                - develop
              ignore:
                - master
